# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Prof. José Dihego
email: josedihego@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Professor at Federal Institute of Education, Science and Technology of Bahia - IFBA (since 2010). Education: Graduated (2008), Master (2010) and Doctorate (2016) in Computer Science, all three at CIn-UFPE. Interested in Formal Methods, Programming Languages ​​and Mobile Development. 
twitter_username: 
github_username: josedihego
minimal_mistakes_skin: contrast
#minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

search: true

lunr:
  search_within_pages: true

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: false
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache



author:
  name   : "José Dihego"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Professor at <a href='https://portal.ifba.edu.br/' target='_blank'>IFBA</a> (since 2010).<br>Graduated (2008), Master (2010) and Doctorate (2016) in Computer Science, all three at <a href='https://www.cin.ufpe.br' target='_blank'>CIn-UFPE</a>"
  links:
  - label: "Email"
    icon: "fas fa-fw fa-envelope"
    url: "mailto:josedihego@gmail.com"
  - label: "Google Classroom"
    icon: "fas fa-fw fa-link"
    url: "https://classroom.google.com/u/1/"
    new_tab: true
  #- label: "YouTube Channel"
  #  icon: "fab fa-fw fa-youtube"
  #  url: "https://www.youtube.com/@josedihego"
  #  new_tab: true
  - label: "LinkedIn"
    icon: "fab fa-fw fa-linkedin"
    url: "https://www.linkedin.com/in/josedihego"
    new_tab: true
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/josedihego"
    new_tab: true
  - label: "My Books on Amazon"
    icon: "fab fa-fw fa-amazon"
    url: "https://www.amazon.com/author/josedihego"
    new_tab: true
  - label: "Lattes CV"
    icon: "fas fa-fw fa-link"
    url: "http://lattes.cnpq.br/1085956076115293"
    new_tab: true


footer:
  links:
  - label: "Email"
    icon: "fas fa-fw fa-envelope"
    url: "mailto:josedihego@gmail.com"
  - label: "Google Classroom"
    icon: "fas fa-fw fa-link"
    url: "https://classroom.google.com/u/1/"
    new_tab: true
  #- label: "YouTube"
  #  icon: "fab fa-fw fa-youtube"
  #  url: "https://www.youtube.com/@josedihego"
  #  new_tab: true
  - label: "LinkedIn"
    icon: "fab fa-fw fa-linkedin"
    url: "https://www.linkedin.com/in/josedihego"
    new_tab: true
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/josedihego"
    new_tab: true
  - label: "Amazon"
    icon: "fab fa-fw fa-amazon"
    url: "https://www.amazon.com/author/josedihego"
    new_tab: true
  - label: "Lattes CV"
    icon: "fas fa-fw fa-link"
    url: "http://lattes.cnpq.br/1085956076115293"
    new_tab: true


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      mathjax: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  news:
    output: true
    permalink: /news/:path/
    
header:
  navigation: true
  responsive_navigation: true # Ensure this is set
